{
  mkReapackPackage,
  stdenv,
  fetchurl,
  lib,
}: let
  imports = [
    ./acendan-scripts.nix
    ./albertov5-reapertools.nix
    ./amelianceskymusic-scripts.nix
    ./archie-reascripts.nix
    ./audiokinetic.nix
    ./beaunus-scripts.nix
    ./bfut-reascripts.nix
    ./binbinhfr-scripts.nix
    ./birdbird-jsfx.nix
    ./birdbird-reascript-testing.nix
    ./birdbird-scripts.nix
    ./bsmith96-scripts.nix
    ./chmaha-airwindows-jsfx-ports.nix
    ./chmaha-scripts.nix
    ./chokehold-jsfx.nix
    ./chtammik-reaper-scripts.nix
    ./claudiohbsantos-scripts.nix
    ./daniel-lumertz-scripts.nix
    ./dfk-reaper-scripts.nix
    ./erriez.nix
    ./eugene27771-reascripts.nix
    ./fernsehmull-scripts.nix
    ./ftc-tools.nix
    ./fx-devices.nix
    ./geraint-s-jsfx.nix
    ./helgoboss-projects.nix
    ./ix.nix
    ./joabe-lopes-multitrack-show-creation.nix
    ./jreng.nix
    ./juan-r-s-reaperism.nix
    ./kawa-script2.nix
    ./kawa-scripts.nix
    ./leandro-facchinetti.nix
    ./lkc-tools.nix
    ./me2beats-scripts.nix
    ./mespotine-scripts-and-extensions.nix
    ./mpl-scripts.nix
    ./mrlimbic-scripts.nix
    ./n0ne-scripts.nix
    ./neutronic-scripts.nix
    ./nofish-reascripts.nix
    ./outboarder-scripts.nix
    ./peloreaper.nix
    ./ply-scripts.nix
    ./przemoc-s-reascripts.nix
    ./radio-toolkit.nix
    ./rcjach-scripts.nix
    ./reaperwrb.nix
    ./reateam-extensions.nix
    ./reateam-jsfx.nix
    ./reateam-langpacks.nix
    ./reateam-scripts.nix
    ./reateam-themes.nix
    ./reaticulate.nix
    ./rejj.nix
    ./robu-scripts.nix
    ./saike-tools.nix
    ./scripts-by-lemerchand.nix
    ./sexan-scripts.nix
    ./sockmonkey72-scripts.nix
    ./sonicanomaly-jsfx.nix
    ./souk21-reapack.nix
    ./stevie-scripts.nix
    ./steviekeys-jsfx.nix
    ./suzuki-scripts.nix
    ./tack-scripts.nix
    ./tilr.nix
    ./tjf-scripts.nix
    ./tormy-van-cool-reapack-scripts.nix
    ./tracker-tools.nix
    ./tukan.nix
    ./x-raym-midi-makey-makey.nix
    ./x-raym-scripts.nix
    ./yannick-reascripts.nix
    ./zaibuyidao-scripts.nix
  ];
  importedPackages = map (path: import path {inherit mkReapackPackage stdenv fetchurl;}) imports;
in
  lib.foldl lib.mergeAttrs {} importedPackages
